REGION = [
    ("ASH", "Ashanti Region"),
    ("AHA", "Ahafo Region"),
    ("BON", "Bono East Region"),
    ("CEN", "Central Region"),
    ("EAS", "Eastern Region"),
    ("GRE", "Greater Accra Region"),
    ("NTN", "Northern Region"),
    ("NEA", "North East Region"),
    ("SVA", "Savannah Region"),
    ("UPW", "Upper West Region"),
    ("WES", "Western Region"),
    ("UPE", "Upper East Region"),
    ("VOL", "Volta Region"),
    ("WNO", "Western North Region"),
    ("OTI", "Oti Region"),
]